name: Deploy dev

on:
  push:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEPLOY_URL: 'https://dev.championship.dance'
          envkey_NEXT_PUBLIC_PAYPAL_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_PAYPAL_CLIENT_ID_DEV }}
          envkey_PAYPAL_SECRET: ${{ secrets.PAYPAL_SECRET_DEV }}
          envkey_PAYPAL_API_URL: ${{ secrets.PAYPAL_API_URL_DEV }}
          envkey_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY_DEV }}
          envkey_STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY_DEV }}
          envkey_SENDINBLUE_SECRET: ${{ secrets.SENDINBLUE_SECRET }}
          envkey_NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          envkey_NOTION_DATABASE_LIVE: ${{ secrets.NOTION_DATABASE_DEV }}
          envkey_FTP_HOST: ${{ secrets.FTP_HOST_DEV }}
          envkey_FTP_USER: ${{ secrets.FTP_USER_DEV }}
          envkey_FTP_PASSWORD: ${{ secrets.FTP_PASSWORD_DEV }}
          envkey_FTP_DIR: ${{ secrets.FTP_DIR_DEV }}
          envkey_ADMIN_PIN: ${{ secrets.ADMIN_PIN_DEV }}
          envkey_FTP_PHOTO_DIR: ${{ secrets.FTP_PHOTO_DIR_DEV }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_IMAGE_NAME }}:latest-dev .

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_IMAGE_NAME }}:latest-dev

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSHHOST }}
          username: ${{ secrets.SSHUSER }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.SSHPASS }}
          script: |
            docker login --username=${{ github.actor }} --password=${{ secrets.GITHUB_TOKEN }} ghcr.io
            docker pull ${{ secrets.DOCKER_IMAGE_NAME }}:latest-dev
            docker stop championship-dev
            docker rm championship-dev
            docker run -d -p 49168:3000 --name=championship-dev --restart=always --pull=always ${{ secrets.DOCKER_IMAGE_NAME }}:latest-dev
            docker system prune -f
